### ISSUE TITLE
Unable to Download AVCVideoCap or FireWire SDK

### ISSUE THREAD

**Issue by GregH18** [WSU-CDSC/Documentation#1]
Hi @privatezero , 

I'm a novice GitHub user and media archiving grad student, and a colleague pointed me to this guide for miniDV capture. I am currently working on my thesis project which includes preserving my family home movies, and I have several miniDV tapes that I want to transfer.

I have tested using iMovie which allows me to capture the content, but it transcodes the video stream to either a ProRes or MP4 file format, which is not native to the original miniDV tapes (as I understand miniDV is in a DVC format). The only other software to do this that I'm aware of is LiveCapturePlus, but that has been discontinued, support is no longer existent, and even when trying to download that, I was unable to get the software to run. 

So that brings me to this guide. I have also been having troubles getting the software. When I follow the Apple Developer Link in this guide and search for both `firewire` and `firewire sdk`, first, there are many links and I'm not sure which to follow. And then, I poked around the developer website and did some research online,  and I haven't found any other troubleshooting documentation. As a matter of fact, I have run into comments that say the Firewire software is no longer available. 

On the other hand, when looking through the FireWire Release Notes link (https://developer.apple.com/library/content/releasenotes/Darwin/RN-FireWire/index.html#//apple_ref/doc/uid/TP40007716), it suggests to install in Terminal this command `sudo nvram boot-args="debug=146 kdp_match_name=firewire"` to enable firewire. I have done this, but now I don't know how to access the AVCVideoCap.

So my questions at last: do you know if I'm on the right track? If so, how do I access AVCVideoCap? Is there an easier way to download this software? Did I even download/enable the correct application?

Any feedback would be helpful, and I really appreciate this workflow guide! I don't think there are many folks are doing DV preservation, or documenting it for that matter, and this has been interesting and useful for me with my DV preservation project.

Thanks in advance!

**Comment by GregH18** [comment]
Update: I took a 24-hour hiatus which I guess allowed me to look at this with fresh eyes. Long story short, I found the FireWire SDK 26 by searching at this link: https://developer.apple.com/download/more/ 

I think I have resolved this issue, but I haven't tried capturing video yet.

**Comment by privatezero** [comment]
Hi @GregH18! Glad you were able to find the download! Apple did a very good job at burying it :/

I'll have to change the explanation to make it a little more explicit - thanks for pointing this out! 

I recently had a colleague who downloaded AVCVideoCap and was having problems with it not capturing certain tapes while working fine on others - I would be interested to hear your experience! My only other advice is that if you are not using a playback machine that has a built in monitor, you will have to plug in an external if you want to monitor your capture as AVCVideoCap has no built in viewing. (Maybe you have noticed this already).

**Comment by privatezero** [comment]
Closing this with changes made in https://github.com/WSU-CDSC/Documentation/commit/3cce033aaa19f5b8fb1f986222007aa0116de5c4. Feel free to hit me up with any questions at `andrew dot weaver at wsu dot edu`!

**Comment by dhavalvoraa** [comment]
Which version of macOS did you use, because the sdk can no longer be installed in the newest macOS 10.15.6

**Comment by privatezero** [comment]
Hi @dhavalvoraa - yeah, Catalina broke a lot of things. I'm pretty sure that anything prior to Catalina should work. Also - if you are trying to capture DV, take a look at the [vrecord project](https://github.com/amiaopensource/vrecord)! It is integrating new changes to the FFmpeg [avfoundation device](https://ffmpeg.org/ffmpeg-devices.html#avfoundation) that allow capture of DV in Catalina.
