### ISSUE TITLE
Cannot find AVCVideoCap 

### ISSUE THREAD

**Issue by DaleLore** [WSU-CDSC/Documentation#2]
I tried to look up AVCVideoCap at the Apple Developer link and I cannot find it. It seems to be no longer available. Does anyone have info about AVCVideoCap or maybe the original download to share?

**Comment by privatezero** [comment]
Hi @DaleLore - I just took a look and can confirm that it is still there as part of the Firewire SDK, just is __VERY__ buried. I suggest you start again from the top page, and make sure to search the "See More Downloads" section for `Firewire`. Good luck, and let me know if you still can't find it!

**Comment by DaleLore** [comment]
Thanks @privatezero! That definitely helped. You're right, it's super buried but found! Thanks for your help!
